#!/usr/bin/env bash
# 为指定 xmake 版本批量生成注解 orphan 分支（xmake/<version>，单根提交）并推送。
#
# 用法（在 xmake-types 仓库根、main 分支上执行）:
#   tools/gen_release.sh 3.1.1 3.0.9 2.9.9 ...
#
# 环境变量：
#   FORCE_REGENERATE  设为 1 时重生成已存在的远程分支并 force-push
#   XMAKE_DOCS_REPO  xmake-io/xmake-docs 本地 clone（默认 /tmp/xmake-docs，需含足够历史）
#   XMAKE_SRC_CACHE  xmake 源码缓存目录（默认 /tmp/xmake-src，tarball 只下载一次）
#   XMAKE_GEN_OUT    生成产物保留目录（默认 /tmp/xmake-gen，供抽查验证）
#   https_proxy      下载/推送代理（网络不稳时 export https_proxy=http://127.0.0.1:7890）
#
# 流程（每个版本）：下载 tarball（带重试）→ gen_annotations.py --docs →
#   orphan 分支 xmake/<version> 单根提交（library/ + apis.json + MANIFEST.md）→ push。
# 已存在的远程分支默认跳过；FORCE_REGENERATE=1 时覆盖它；某版本失败则记录并继续下一个。
set -uo pipefail

REPO="$(git rev-parse --show-toplevel)"
DOCS="${XMAKE_DOCS_REPO:-/tmp/xmake-docs}"
SRC_CACHE="${XMAKE_SRC_CACHE:-/tmp/xmake-src}"
GEN_OUT="${XMAKE_GEN_OUT:-/tmp/xmake-gen}"
FORCE_REGENERATE="${FORCE_REGENERATE:-0}"
PROXY_GIT=()
[ -n "${https_proxy:-}" ] && PROXY_GIT=(-c "http.proxy=${https_proxy}")

FAILED=()
SKIPPED=()

fetch_src() {  # $1=版本，输出源码根路径；失败返回非零
    local ver="$1" dir="$SRC_CACHE/xmake-$1"
    if [ -d "$dir/xmake/core" ]; then echo "$dir"; return 0; fi
    local tarball="$SRC_CACHE/v$ver.tar.gz"
    mkdir -p "$SRC_CACHE"
    echo ">> 下载 v$ver tarball" >&2
    if ! curl -fsSL --retry 3 --retry-delay 3 -o "$tarball" \
            "https://github.com/xmake-io/xmake/archive/refs/tags/v$ver.tar.gz" >&2; then
        echo "!! v$ver tarball 下载失败" >&2; return 1
    fi
    rm -rf "$dir" "$dir.tmp"
    mkdir -p "$dir.tmp"
    tar xzf "$tarball" -C "$dir.tmp" || { echo "!! v$ver 解压失败" >&2; return 1; }
    mv "$dir.tmp/xmake-$ver" "$dir" && rm -rf "$dir.tmp"
    [ -d "$dir/xmake/core" ] || { echo "!! v$ver 源码布局不符（缺 xmake/core）" >&2; return 1; }
    echo "$dir"
}

gen_one() {  # $1=版本
    local ver="$1"
    if [ "$FORCE_REGENERATE" != "1" ] && git ls-remote --exit-code origin "xmake/$ver" >/dev/null 2>&1; then
        echo "== v$ver: 远程分支已存在，跳过"; SKIPPED+=("$ver"); return 0
    fi
    if [ "$FORCE_REGENERATE" = "1" ]; then
        echo "== v$ver: 开始覆盖生成"
    else
        echo "== v$ver: 开始生成"
    fi
    local src date out log docs_commit
    src="$(fetch_src "$ver")" || { FAILED+=("$ver (源码获取失败)"); return 1; }
    # 生成器自身也会用 gh 兜底，这里显式取日期以便写入 MANIFEST
    date="$(gh release view "v$ver" --repo xmake-io/xmake --json publishedAt -q .publishedAt 2>/dev/null || true)"
    out="$GEN_OUT/$ver"; log="$GEN_OUT/$ver.log"
    rm -rf "$out"; mkdir -p "$out"
    if ! python3 "$REPO/tools/gen_annotations.py" "$src" "$ver" "$out" --docs "$DOCS" \
            ${date:+--release-date "$date"} 2>&1 | tee "$log"; then
        FAILED+=("$ver (生成器失败，见 $log)"); return 1
    fi
    docs_commit="$(git -C "$DOCS" rev-parse HEAD)"

    # 建 orphan 分支（单根提交）
    cd "$REPO"
    git switch -q --orphan "xmake/$ver"
    git rm -rfq . 2>/dev/null || true
    cp -r "$out/library" .; cp "$out/apis.json" .
    {
        echo "# xmake/$ver"
        echo
        echo "- xmake 版本：$ver（源码：xmake-io/xmake v$ver tarball）"
        [ -n "$date" ] && echo "- 发布日期：$date"
        echo "- 注解内容：纯源码生成 + 官方文档合并，由 tools/gen_annotations.py（main 分支 $(git rev-parse --short origin/main)）生成"
        echo "- 文档合并层：xmake-io/xmake-docs @ $docs_commit（按发布日期映射：不晚于发布日期的最后一个 commit；zh 镜像优先、英文兜底）"
        echo "- 生成统计："
        echo '```'
        grep -E '^(文档|DSL|  |实例类|沙箱模块)' "$log" || cat "$log"
        echo '```'
        echo "- 生成时间：$(date -Iseconds)"
    } > MANIFEST.md
    git add library apis.json MANIFEST.md
    git -c user.name=AzurIce -c user.email=azurice@users.noreply.github.com \
        commit -qm "xmake $ver annotations (generated by tools/gen_annotations.py @ main)"
    local push_options=()
    [ "$FORCE_REGENERATE" = "1" ] && push_options+=(--force)
    git "${PROXY_GIT[@]}" push -q "${push_options[@]}" origin "xmake/$ver" || {
        FAILED+=("$ver (push 失败)"); git switch -q main; return 1;
    }
    git switch -q main
    echo "== v$ver: 完成 -> $(git rev-parse --short xmake/$ver)"
}

[ $# -ge 1 ] || { echo "用法: $0 <版本...>"; exit 1; }
cd "$REPO"
[ -z "$(git status --porcelain)" ] || { echo "!! 工作区不干净，请先提交/清理"; exit 1; }
git switch -q main || exit 1
for v in "$@"; do gen_one "$v"; done

echo
echo "===== 汇总 ====="
[ ${#SKIPPED[@]} -gt 0 ] && echo "跳过: ${SKIPPED[*]}"
[ ${#FAILED[@]} -gt 0 ] && { echo "失败: ${FAILED[*]}"; exit 1; }
echo "全部成功"
